name: Update README with Engineering Blogs

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Spotify
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://engineering.atspotify.com/feed/"
          max_post_count: 2
          template: "- **[$title]($url)** <sub>$date</sub>$newline"
          readme_path: "README.md"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          comment_tag_name: "SPOTIFY-BLOG"

      - name: Netflix
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://netflixtechblog.com/feed/"
          max_post_count: 2
          template: "- **[$title]($url)** <sub>$date</sub>$newline"
          readme_path: "README.md"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          comment_tag_name: "NETFLIX-BLOG"
